---
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
first-line-h1: false
blanks-around-fences: false
line-length:
  line_length: 148
  code_block_line_length: 148
no-inline-html:
  allowed_elements:
    - details
    - summary
