name: Build and test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - master
  schedule:
    # We want to run right after the `latest` image is published.
    # So, let's do it an hour right after. Look the schedule of publishing here:
    # https://github.com/alexhumphreys/idris2-dockerfile/blob/main/.github/workflows/docker-image.yml
    - cron: '0 1 * * *'

defaults:
  run:
    shell: bash

jobs:

  read-ver:
    name: Aquire compiler version
    runs-on: ubuntu-latest
    env:
      IDRIS_VERSION_FILE: .idris-version
    outputs:
      idris-ver: ${{ steps.read-ver.outputs.idris-ver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read the version
        id: read-ver
        run: sed 's/^/::set-output name=idris-ver::/' < "${IDRIS_VERSION_FILE}"

  build:
    name: Build and test `coop`
    needs: read-ver
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        idris-version: # git describe --tags
          - ${{ needs.read-ver.outputs.idris-ver }}
          - latest
    container: snazzybucket/idris2api:${{ matrix.idris-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build `coop`
        run: make coop
      - name: Test `coop`
        run: make test-coop
