---
name: Build and test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  PACK_DIR: /root/.pack

jobs:

  select-pack-collection:
    name: Select `pack` collection
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Switch to appropriate `pack` collection
        run: pack switch "$( if [[ '${{ github.event_name }}' == 'schedule' ]]; then echo latest; else cat .pack-collection; fi )"
      - name: Save `pack` state
        uses: actions/upload-artifact@v3
        with:
          name: pack-state
          path: ${PACK_DIR}

  build:
    name: Build `coop`
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    needs: select-pack-collection
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore `pack` state
        uses: actions/download-artifact@v3
        with:
          name: pack-state
          path: ${PACK_DIR}
      - name: Build `coop`
        run: pack build coop
      - name: Save `pack` state
        uses: actions/upload-artifact@v3
        with:
          name: pack-state
          path: ${PACK_DIR}

  test:
    name: Test `coop`
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore `pack` state
        uses: actions/download-artifact@v3
        with:
          name: pack-state
          path: ${PACK_DIR}
      - name: Test `coop`
        run: pack test coop
