name: Build and test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - master
  schedule:
    # We want to run right after the `latest` image is published.
    # So, let's do it an hour right after. Look the schedule of publishing here:
    # https://github.com/alexhumphreys/idris2-dockerfile/blob/main/.github/workflows/docker-image.yml
    - cron: '0 1 * * *'

concurrency:
￼ group: ${{ github.ref }}
￼ cancel-in-progress: true

defaults:
  container: ghcr.io/stefan-hoeck/idris2-pack:latest
  runs-on: ubuntu-latest
  run:
    shell: bash

env:
  PACK_DIR: /root/.pack

jobs:

  select-pack-collection:
    name: Select `pack` collection
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Switch to appropriate `pack` collection
        run:  pack switch "$( [[ '${{ github.event_name }}' == 'schedule' ]] && echo latest || cat .pack-collection )"
      - name: Save `pack` state
        uses: actions/upload-artifact@v3
        with:
          name: pack-state
          path: ${PACK_DIR}

  build:
    name: Build `coop`
    needs: select-pack-collection
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore `pack` state
        uses: actions/download-artifact@v3
        with:
          name: pack-state
          path: ${PACK_DIR}
      - name: Build `coop`
        run:  pack build coop
      - name: Save `pack` state
        uses: actions/upload-artifact@v3
        with:
          name: pack-state
          path: ${PACK_DIR}

  test:
    name: Test `coop`
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore `pack` state
        uses: actions/download-artifact@v3
        with:
          name: pack-state
          path: ${PACK_DIR}
      - name: Test `coop`
        run:  pack test coop
